version: '3.4'

services:
  app:
    container_name: app
    command: npm start
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    networks:
      - fullcycle-node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
    entrypoint: "docker-entrypoint.sh"
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    networks:
      - fullcycle-node
    ports:
      - 8080:80
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    networks:
      - fullcycle-node
    volumes:
      - ./docker/mysql/var:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root

networks:
  fullcycle-node:
    driver: bridge